In [1]:
import pandas as pd
import pathlib as path

In [2]:
data_raw = path.Path("../data/raw")
retail = data_raw / "Online-Retail.xlsx"
print(retail)
print(retail.exists())

..\data\raw\Online-Retail.xlsx
True

In [3]:
df_retail = pd.read_excel(retail)
df_retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
df_retail.shape

(541909, 8)

In [5]:
df_retail.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

In [6]:
df_retail.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [7]:
df_retail.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
df_retail.duplicated().sum()

np.int64(5268)

In [9]:
df_retail.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
541904    False
541905    False
541906    False
541907    False
541908    False
Length: 541909, dtype: bool

In [10]:
for coluna in df_retail.columns:
    qtd = df_retail[coluna].duplicated().sum()
    print(f"{coluna}: {qtd} valor(es) duplicado(s)")

InvoiceNo: 516009 valor(es) duplicado(s)
StockCode: 537839 valor(es) duplicado(s)
Description: 537685 valor(es) duplicado(s)
Quantity: 541187 valor(es) duplicado(s)
InvoiceDate: 518649 valor(es) duplicado(s)
UnitPrice: 540279 valor(es) duplicado(s)
CustomerID: 537536 valor(es) duplicado(s)
Country: 541871 valor(es) duplicado(s)

In [11]:
df_retail.loc[df_retail['CustomerID'].isnull()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
541536,581498,85099B,JUMBO BAG RED RETROSPOT,5,2011-12-09 10:26:00,4.13,NaN,United Kingdom
541537,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,2011-12-09 10:26:00,4.13,NaN,United Kingdom
541538,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,2011-12-09 10:26:00,4.96,NaN,United Kingdom
541539,581498,85174,S/4 CACTI CANDLES,1,2011-12-09 10:26:00,10.79,NaN,United Kingdom
541540,581498,DOT,DOTCOM POSTAGE,1,2011-12-09 10:26:00,1714.17,NaN,United Kingdom

In [12]:
df_retail['Country'].unique()

<StringArray>
[      'United Kingdom',               'France',            'Australia',
          'Netherlands',              'Germany',               'Norway',
                 'EIRE',          'Switzerland',                'Spain',
               'Poland',             'Portugal',                'Italy',
              'Belgium',            'Lithuania',                'Japan',
              'Iceland',      'Channel Islands',              'Denmark',
               'Cyprus',               'Sweden',              'Austria',
               'Israel',              'Finland',              'Bahrain',
               'Greece',            'Hong Kong',            'Singapore',
              'Lebanon', 'United Arab Emirates',         'Saudi Arabia',
       'Czech Republic',               'Canada',          'Unspecified',
               'Brazil',                  'USA',   'European Community',
                'Malta',                  'RSA']
Length: 38, dtype: str

In [13]:
df_retail['Country'].value_counts()

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [14]:
quantidade_min = df_retail['Quantity'].min()
quantidade_max = df_retail['Quantity'].max()

print("Menor quantidade:", quantidade_min)
print("Maior quantidade:", quantidade_max)

Menor quantidade: -80995
Maior quantidade: 80995

In [15]:
quantidade_negativa = df_retail[df_retail['Quantity'] < 0]
quantidade_negativa

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

In [16]:
quantidade_negativa.shape

(10624, 8)

In [17]:
quantidade_negativa.head(50)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,2010-12-01 14:30:00,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,2010-12-01 14:30:00,0.85,17841.0,United Kingdom
1973,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,2010-12-01 14:33:00,1.95,12472.0,Germany
1974,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,2010-12-01 14:33:00,1.65,12472.0,Germany
1975,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,2010-12-01 14:33:00,2.95,12472.0,Germany
1976,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,2010-12-01 14:33:00,1.25,12472.0,Germany
1977,C536548,22654,DELUXE SEWING KIT,-1,2010-12-01 14:33:00,5.95,12472.0,Germany
1978,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,2010-12-01 14:33:00,9.95,12472.0,Germany
1979,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,2010-12-01 14:33:00,1.65,12472.0,Germany
1980,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,2010-12-01 14:33:00,0.85,12472.0,Germany
1981,C536548,22077,6 RIBBONS RUSTIC CHARM,-6,2010-12-01 14:33:00,1.65,12472.0,Germany
1982,C536548,22631,CIRCUS PARADE LUNCH BOX,-1,2010-12-01 14:33:00,1.95,12472.0,Germany
1983,C536548,22168,ORGANISER WOOD ANTIQUE WHITE,-2,2010-12-01 14:33:00,8.50,12472.0,Germany
1984,C536548,21218,RED SPOTTY BISCUIT TIN,-3,2010-12-01 14:33:00,3.75,12472.0,Germany
1985,C536548,20957,PORCELAIN HANGING BELL SMALL,-1,2010-12-01 14:33:00,1.45,12472.0,Germany
1986,C536548,22580,ADVENT CALENDAR GINGHAM SACK,-4,2010-12-01 14:33:00,5.95,12472.0,Germany
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.00,NaN,United Kingdom
3170,C536606,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-2,2010-12-02 09:10:00,2.95,14092.0,United Kingdom
3338,C536622,22752,SET 7 BABUSHKA NESTING BOXES,-2,2010-12-02 10:37:00,8.50,12471.0,Germany
3410,C536625,22839,3 TIER CAKE TIN GREEN AND CREAM,-2,2010-12-02 10:46:00,14.95,14766.0,United Kingdom
3693,C536642,21463,MIRRORED DISCO BALL,-1,2010-12-02 11:56:00,5.95,14390.0,United Kingdom
3911,C536734,22780,LIGHT GARLAND BUTTERFILES PINK,-4,2010-12-02 12:50:00,4.25,16042.0,United Kingdom
3912,C536734,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,-1,2010-12-02 12:50:00,7.95,16042.0,United Kingdom
3919,C536737,22798,ANTIQUE GLASS DRESSING TABLE POT,-2,2010-12-02 13:05:00,2.95,15922.0,United Kingdom
4287,C536757,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,-9360,2010-12-02 14:23:00,0.03,15838.0,United Kingdom
4288,C536758,21314,SMALL GLASS HEART TRINKET POT,-1,2010-12-02 14:25:00,2.10,13767.0,United Kingdom
4306,C536760,22175,PINK OWL SOFT TOY,-1,2010-12-02 14:29:00,2.95,17547.0,United Kingdom
4307,C536760,22273,FELTCRAFT DOLL MOLLY,-3,2010-12-02 14:29:00,2.95,17547.0,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.00,NaN,United Kingdom
4836,C536807,22501,PICNIC BASKET WICKER LARGE,-2,2010-12-02 16:45:00,9.95,15834.0,United Kingdom
4837,C536807,22778,GLASS CLOCHE SMALL,-1,2010-12-02 16:45:00,3.95,15834.0,United Kingdom
4853,C536812,22578,WOODEN STAR CHRISTMAS SCANDINAVIAN,-36,2010-12-02 16:58:00,0.85,16546.0,United Kingdom
4854,C536812,22574,HEART WOODEN CHRISTMAS DECORATION,-192,2010-12-02 16:58:00,0.72,16546.0,United Kingdom
4855,C536812,22593,CHRISTMAS GINGHAM STAR,-144,2010-12-02 16:58:00,0.72,16546.0,United Kingdom
4856,C536812,22595,CHRISTMAS GINGHAM HEART,-144,2010-12-02 16:58:00,0.72,16546.0,United Kingdom
4857,C536812,22588,CARD HOLDER GINGHAM HEART,-192,2010-12-02 16:58:00,2.10,16546.0,United Kingdom
4858,C536812,22130,PARTY CONE CHRISTMAS DECORATION,-144,2010-12-02 16:58:00,0.72,16546.0,United Kingdom
4876,C536814,21527,RED RETROSPOT TRADITIONAL TEAPOT,-2,2010-12-02 17:03:00,7.95,13958.0,United Kingdom
4877,C536814,72799E,IVORY PILLAR CANDLE SILVER FLOCK,-6,2010-12-02 17:03:00,2.95,13958.0,United Kingdom
4878,C536814,85066,CREAM SWEETHEART MINI CHEST,-2,2010-12-02 17:03:00,12.75,13958.0,United Kingdom

In [18]:
quantidade_negativa.tail(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540082,C581464,71477,COLOURED GLASS STAR T-LIGHT HOLDER,-6,2011-12-08 18:57:00,3.95,15951.0,United Kingdom
540083,C581465,23660,HENRIETTA HEN MUG,-2,2011-12-08 18:59:00,1.65,15755.0,United Kingdom
540084,C581465,22171,3 HOOK PHOTO SHELF ANTIQUE WHITE,-1,2011-12-08 18:59:00,8.50,15755.0,United Kingdom
540085,C581465,21876,POTTERING MUG,-4,2011-12-08 18:59:00,1.65,15755.0,United Kingdom
540086,C581465,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-3,2011-12-08 18:59:00,2.95,15755.0,United Kingdom
540087,C581466,22838,3 TIER CAKE TIN RED AND CREAM,-1,2011-12-08 19:20:00,14.95,13883.0,United Kingdom
540088,C581466,22720,SET OF 3 CAKE TINS PANTRY DESIGN,-2,2011-12-08 19:20:00,4.95,13883.0,United Kingdom
540089,C581466,21216,"SET 3 RETROSPOT TEA,COFFEE,SUGAR",-1,2011-12-08 19:20:00,4.95,13883.0,United Kingdom
540090,C581466,21535,RED RETROSPOT SMALL MILK JUG,-2,2011-12-08 19:20:00,2.55,13883.0,United Kingdom
540091,C581466,21232,STRAWBERRY CERAMIC TRINKET POT,-1,2011-12-08 19:20:00,1.25,13883.0,United Kingdom
540141,C581468,21314,SMALL GLASS HEART TRINKET POT,-10,2011-12-08 19:26:00,2.10,13599.0,United Kingdom
540142,C581468,22098,BOUDOIR SQUARE TISSUE BOX,-12,2011-12-08 19:26:00,0.39,13599.0,United Kingdom
540176,C581470,23084,RABBIT NIGHT LIGHT,-4,2011-12-08 19:28:00,2.08,17924.0,United Kingdom
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2011-12-09 09:27:00,2.08,16446.0,United Kingdom
540448,C581490,22178,VICTORIAN GLASS HANGING T-LIGHT,-12,2011-12-09 09:57:00,1.95,14397.0,United Kingdom
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

In [19]:
clienteid = quantidade_negativa[['CustomerID','InvoiceDate']].value_counts()
clienteid.head(10)

CustomerID  InvoiceDate
12607.0     2011-10-12 16:17:00    101
12415.0     2011-07-19 12:26:00     57
16801.0     2011-03-31 11:58:00     45
14410.0     2011-07-21 13:00:00     41
15514.0     2010-12-10 14:03:00     39
14911.0     2011-10-12 13:15:00     39
15365.0     2011-10-06 19:51:00     36
14146.0     2011-01-28 09:32:00     35
14426.0     2011-07-14 10:19:00     32
16717.0     2011-07-18 14:24:00     31
Name: count, dtype: int64

In [20]:
quantidade_negativa['InvoiceNo'].str.startswith('C').value_counts()

InvoiceNo
True    9288
Name: count, dtype: int64

In [21]:
df_retail[df_retail['Quantity'] == 80995]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446.0,United Kingdom

In [22]:
df_retail[df_retail['Quantity'] == -80995]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2011-12-09 09:27:00,2.08,16446.0,United Kingdom

In [23]:
df_retail['InvoiceNo'].str.startswith('C')

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
541904    NaN
541905    NaN
541906    NaN
541907    NaN
541908    NaN
Name: InvoiceNo, Length: 541909, dtype: object

In [24]:
qtda_na =quantidade_negativa[quantidade_negativa['CustomerID'].isnull()]
qtda_na.shape

(1719, 8)

In [25]:
qtda_null =quantidade_negativa[quantidade_negativa['Description'].isnull()]
qtda_null.shape

(862, 8)

In [26]:
valor_0 =quantidade_negativa[quantidade_negativa['UnitPrice'] == 0]
valor_0.shape

(1336, 8)

In [27]:
valor_0['Description'].value_counts(dropna=False).head(30)

Description
NaN                             862
check                           120
damages                          45
damaged                          42
?                                41
sold as set on dotcom            20
Damaged                          14
thrown away                       9
Unsaleable, destroyed.            9
??                                7
damages?                          5
wet damaged                       5
ebay                              5
smashed                           4
missing                           3
CHECK                             3
wet pallet                        3
Dotcom sales                      2
reverse 21/5/10 adjustment        2
counted                           2
crushed                           2
wet/rusty                         2
printing smudges/thrown away      2
sold as 1                         2
?missing                          2
incorrect stock entry.            2
stock check                       2
adjustment                        2
damages wax                       2
wet rusty                         2
Name: count, dtype: int64

## Análise da coluna Quantity

Foram identificados valores negativos na coluna `Quantity`.

A investigação indicou dois comportamentos distintos:

- Registros com `InvoiceNo` iniciado por `C` representam cancelamentos.
- Foram identificados 9.288 registros desse tipo.
- Foi encontrado um caso em que uma compra de 80.995 unidades foi seguida,
  12 minutos depois, pelo cancelamento das mesmas 80.995 unidades.

Também foram encontrados registros negativos sem o prefixo `C`.

- Esses registros possuem `UnitPrice = 0`.
- As descrições incluem termos como `damaged`, `check`, `thrown away`,
  `missing`, `stock check` e `adjustment`.
- Esses registros aparentam representar ajustes ou baixas de estoque,
  e não vendas.
- Parte desses registros possui `Description` nula e deverá receber
  tratamento específico durante a transformação.

Conclusão: valores negativos não devem ser simplesmente removidos,
pois representam diferentes eventos de negócio.

In [94]:
import os

print(os.getcwd())

c:\Users\Gabriel\Desktop\Datasets\Pratica\online-retail-etl\notebooks

In [95]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))



from src.transform import remove_duplicates
from src.transform import define_cancelamento
from src.transform import define_ajuste_estoque
from src.transform import define_tipo_transacao
from src.transform import calcula_valor_total

In [96]:
df_limpo = remove_duplicates(df_retail)
df_transformado = define_cancelamento(df_limpo)
df_transformado = define_ajuste_estoque(df_transformado)
df_transformado = define_tipo_transacao(df_transformado)
df_transformado = calcula_valor_total(df_transformado)

Registros antes: 541909
Duplicados encontrados: 5268
Registros depois: 536641
Quantidade de registros cancelados: 9251
Quantidade de registros de ajuste de estoque: 1336
Quantidade de vendas: 526054
Quantidade de cancelamentos: 9251
Quantidade de ajustes de estoque: 1336

In [97]:
df_transformado[["InvoiceNo", "Quantity", "cancelado"]].head(20)

   InvoiceNo  Quantity  cancelado
0     536365         6      False
1     536365         6      False
2     536365         8      False
3     536365         6      False
4     536365         6      False
5     536365         2      False
6     536365         6      False
7     536366         6      False
8     536366         6      False
9     536367        32      False
10    536367         6      False
11    536367         6      False
12    536367         8      False
13    536367         6      False
14    536367         6      False
15    536367         3      False
16    536367         2      False
17    536367         3      False
18    536367         3      False
19    536367         4      False

In [98]:
df_transformado["cancelado"].value_counts()

cancelado
False    527390
True       9251
Name: count, dtype: int64

In [99]:
df_transformado = define_ajuste_estoque(df_transformado)

Quantidade de registros de ajuste de estoque: 1336

In [100]:

df_transformado[
    ["InvoiceNo", "Quantity", "UnitPrice", "cancelado", "ajuste_estoque"]
].head(20)

   InvoiceNo  Quantity  UnitPrice  cancelado  ajuste_estoque
0     536365         6       2.55      False           False
1     536365         6       3.39      False           False
2     536365         8       2.75      False           False
3     536365         6       3.39      False           False
4     536365         6       3.39      False           False
5     536365         2       7.65      False           False
6     536365         6       4.25      False           False
7     536366         6       1.85      False           False
8     536366         6       1.85      False           False
9     536367        32       1.69      False           False
10    536367         6       2.10      False           False
11    536367         6       2.10      False           False
12    536367         8       3.75      False           False
13    536367         6       1.65      False           False
14    536367         6       4.25      False           False
15    536367         3       4.95      False           False
16    536367         2       9.95      False           False
17    536367         3       5.95      False           False
18    536367         3       5.95      False           False
19    536367         4       7.95      False           False

In [101]:
df_transformado["ajuste_estoque"].value_counts()

ajuste_estoque
False    535305
True       1336
Name: count, dtype: int64

In [102]:
df_transformado["tipo_transacao"].value_counts()

tipo_transacao
VENDA                526054
CANCELAMENTO           9251
AJUSTE_DE_ESTOQUE      1336
Name: count, dtype: int64

In [103]:
df_transformado.isnull().sum()

InvoiceNo              0
StockCode              0
Description         1454
Quantity               0
InvoiceDate            0
UnitPrice              0
CustomerID        135037
Country                0
cancelado              0
ajuste_estoque         0
tipo_transacao         0
valor_total            0
dtype: int64

In [104]:
df_transformado[
    df_transformado["CustomerID"].isnull()
]["tipo_transacao"].value_counts()

tipo_transacao
VENDA                133322
AJUSTE_DE_ESTOQUE      1336
CANCELAMENTO            379
Name: count, dtype: int64

In [105]:
df_transformado[
    df_transformado["Description"].isnull()
]["tipo_transacao"].value_counts()

tipo_transacao
AJUSTE_DE_ESTOQUE    862
VENDA                592
Name: count, dtype: int64

In [106]:
vendas_sem_descricao = df_transformado[
    (df_transformado["tipo_transacao"]== "VENDA")
    & (df_transformado["Description"].isnull())
]
vendas_sem_descricao[
    ["InvoiceNo",
    "StockCode",
    "Description",
    "Quantity",
    "InvoiceDate",
    "UnitPrice",
    "CustomerID",
    "Country"
    ]
].head(30)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,2010-12-02 14:43:00,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,2010-12-03 15:29:00,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7194,537002,21651,NaN,70,2010-12-03 15:33:00,0.0,NaN,United Kingdom
12008,537361,21777,NaN,5,2010-12-06 12:34:00,0.0,NaN,United Kingdom
13263,537430,85215,NaN,120,2010-12-06 16:05:00,0.0,NaN,United Kingdom
13959,537436,84270,NaN,7,2010-12-06 17:00:00,0.0,NaN,United Kingdom
13960,537437,90167,NaN,10,2010-12-06 17:00:00,0.0,NaN,United Kingdom
13961,537438,22959,NaN,13,2010-12-06 17:00:00,0.0,NaN,United Kingdom
13962,537439,37474,NaN,1,2010-12-06 17:01:00,0.0,NaN,United Kingdom
19625,537872,21595,NaN,1,2010-12-08 18:07:00,0.0,NaN,United Kingdom
19626,537873,37461,NaN,1,2010-12-08 18:07:00,0.0,NaN,United Kingdom
19627,537874,85170A,NaN,1,2010-12-08 18:07:00,0.0,NaN,United Kingdom
19628,537875,20849,NaN,1,2010-12-08 18:08:00,0.0,NaN,United Kingdom
19629,537876,84977,NaN,2,2010-12-08 18:08:00,0.0,NaN,United Kingdom
19630,537877,21661,NaN,1,2010-12-08 18:08:00,0.0,NaN,United Kingdom
19631,537878,72803B,NaN,1,2010-12-08 18:09:00,0.0,NaN,United Kingdom
19999,538001,35958,NaN,10,2010-12-09 11:45:00,0.0,NaN,United Kingdom
20037,538004,22114,NaN,144,2010-12-09 12:11:00,0.0,NaN,United Kingdom
20324,538036,21690,NaN,34,2010-12-09 13:04:00,0.0,NaN,United Kingdom
20330,538038,21488,NaN,8,2010-12-09 13:07:00,0.0,NaN,United Kingdom

In [107]:
vendas_sem_descricao["UnitPrice"].describe()

count    592.0
mean       0.0
std        0.0
min        0.0
25%        0.0
50%        0.0
75%        0.0
max        0.0
Name: UnitPrice, dtype: float64

In [108]:
vendas_sem_descricao["Quantity"].describe()

count     592.000000
mean       54.978041
std       277.207445
min         1.000000
25%         2.000000
50%         6.000000
75%        25.250000
max      5568.000000
Name: Quantity, dtype: float64

In [109]:
print(
    "Preço zero:",
    (vendas_sem_descricao["UnitPrice"] == 0).sum()
)

print(
    "CustomerID nulo:",
    vendas_sem_descricao["CustomerID"].isnull().sum()
)

print(
    "Quantidade positiva:",
    (vendas_sem_descricao["Quantity"] > 0).sum()
)

Preço zero: 592
CustomerID nulo: 592
Quantidade positiva: 592

In [110]:
df_transformado[
    df_transformado["UnitPrice"] == 0
]["tipo_transacao"].value_counts()

tipo_transacao
AJUSTE_DE_ESTOQUE    1336
VENDA                1174
Name: count, dtype: int64

In [111]:
df_transformado[
    df_transformado["UnitPrice"] == 0
][
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "UnitPrice",
        "CustomerID",
        "tipo_transacao"
    ]
].sample(30, random_state=42)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,tipo_transacao
220142,556123,22272,Damaged,-15,0.0,NaN,AJUSTE_DE_ESTOQUE
497819,578476,72807B,????missing,-124,0.0,NaN,AJUSTE_DE_ESTOQUE
521408,580366,22923,FRIDGE MAGNETS LES ENFANTS ASSORTED,6,0.0,NaN,VENDA
332406,566066,15060B,NaN,-52,0.0,NaN,AJUSTE_DE_ESTOQUE
193186,553521,48184,DOORMAT ENGLISH ROSE,1,0.0,NaN,VENDA
382680,569935,90209B,NaN,1,0.0,NaN,VENDA
41485,539856,22512,DOORSTOP RACING CAR DESIGN,1,0.0,NaN,VENDA
320695,565071,84754,NaN,-242,0.0,NaN,AJUSTE_DE_ESTOQUE
50849,540564,22617,"mouldy, thrown away.",-2600,0.0,NaN,AJUSTE_DE_ESTOQUE
280323,561392,79161A,NaN,15,0.0,NaN,VENDA
171724,551450,21410,NaN,-4,0.0,NaN,AJUSTE_DE_ESTOQUE
319907,564926,22968,NaN,9,0.0,NaN,VENDA
115806,546138,21815,?,-300,0.0,NaN,AJUSTE_DE_ESTOQUE
357357,568085,84912A,NaN,2,0.0,NaN,VENDA
154799,549948,37488A,damaged,-1,0.0,NaN,AJUSTE_DE_ESTOQUE
192291,553396,22423,damages,-21,0.0,NaN,AJUSTE_DE_ESTOQUE
38262,539495,22591,NaN,36,0.0,NaN,VENDA
489205,577972,84663A,NaN,1,0.0,NaN,VENDA
89118,543827,84406B,incorrectly made-thrown away.,-64,0.0,NaN,AJUSTE_DE_ESTOQUE
269195,560440,84029E,NaN,-1,0.0,NaN,AJUSTE_DE_ESTOQUE
480177,577263,47503H,found,66,0.0,NaN,VENDA
104273,545160,22625,RED KITCHEN SCALES,1,0.0,NaN,VENDA
375309,569458,20984,NaN,58,0.0,NaN,VENDA
128463,547335,20934,NaN,-15,0.0,NaN,AJUSTE_DE_ESTOQUE
242420,558340,22676,FRENCH BLUE METAL DOOR SIGN 1,3,0.0,NaN,VENDA
205713,554829,20801,NaN,6,0.0,NaN,VENDA
150627,549506,22415,NaN,-31,0.0,NaN,AJUSTE_DE_ESTOQUE
14362,537534,22432,WATERING CAN PINK BUNNY,1,0.0,NaN,VENDA
229336,557031,21447,NaN,-65,0.0,NaN,AJUSTE_DE_ESTOQUE
500145,578733,21643,damaged,-9,0.0,NaN,AJUSTE_DE_ESTOQUE

In [112]:
vendas_preco_zero = df_transformado[
    (df_transformado["tipo_transacao"] == "VENDA")
    & (df_transformado["UnitPrice"] == 0)
]

vendas_preco_zero.shape

(1174, 12)

In [113]:
vendas_preco_zero["CustomerID"].isnull().value_counts()

CustomerID
True     1134
False      40
Name: count, dtype: int64

In [114]:
vendas_preco_zero["Description"].isnull().value_counts()

Description
True     592
False    582
Name: count, dtype: int64

In [115]:
vendas_preco_zero[
    vendas_preco_zero["CustomerID"].notnull()
][
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
].head(30)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,0.0,12647.0,Germany
33576,539263,22580,ADVENT CALENDAR GINGHAM SACK,4,0.0,16560.0,United Kingdom
40089,539722,22423,REGENCY CAKESTAND 3 TIER,10,0.0,14911.0,EIRE
47068,540372,22090,PAPER BUNTING RETROSPOT,24,0.0,13081.0,United Kingdom
47070,540372,22553,PLASTERS IN TIN SKULLS,24,0.0,13081.0,United Kingdom
56674,541109,22168,ORGANISER WOOD ANTIQUE WHITE,1,0.0,15107.0,United Kingdom
86789,543599,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,16,0.0,17560.0,United Kingdom
130188,547417,22062,CERAMIC BOWL WITH LOVE HEART DESIGN,36,0.0,13239.0,United Kingdom
139453,548318,22055,MINI CAKE STAND HANGING STRAWBERY,5,0.0,13113.0,United Kingdom
145208,548871,22162,HEART GARLAND RUSTIC PADDED,2,0.0,14410.0,United Kingdom
157042,550188,22636,CHILDS BREAKFAST SET CIRCUS PARADE,1,0.0,12457.0,Switzerland
187613,553000,47566,PARTY BUNTING,4,0.0,17667.0,United Kingdom
198383,554037,22619,SET OF 6 SOLDIER SKITTLES,80,0.0,12415.0,Australia
279324,561284,22167,OVAL WALL MIRROR DIAMANTE,1,0.0,16818.0,United Kingdom
282912,561669,22960,JAM MAKING SET WITH JARS,11,0.0,12507.0,Spain
285657,561916,M,Manual,1,0.0,15581.0,United Kingdom
298054,562973,23157,SET OF 6 NATIVITY MAGNETS,240,0.0,14911.0,EIRE
314745,564651,23270,SET OF 2 CERAMIC PAINTED HEARTS,96,0.0,14646.0,Netherlands
314746,564651,23268,SET OF 2 CERAMIC CHRISTMAS REINDEER,192,0.0,14646.0,Netherlands
314747,564651,22955,36 FOIL STAR CAKE CASES,144,0.0,14646.0,Netherlands
314748,564651,21786,POLKADOT RAIN HAT,144,0.0,14646.0,Netherlands
358655,568158,PADS,PADS TO MATCH ALL CUSHIONS,1,0.0,16133.0,United Kingdom
361825,568384,M,Manual,1,0.0,12748.0,United Kingdom
379913,569716,22778,GLASS CLOCHE SMALL,2,0.0,15804.0,United Kingdom
395529,571035,M,Manual,1,0.0,12446.0,RSA
420404,572893,21208,PASTEL COLOUR HONEYCOMB FAN,5,0.0,18059.0,United Kingdom
436428,574138,23234,BISCUIT TIN VINTAGE CHRISTMAS,216,0.0,12415.0,Australia
436597,574175,22065,CHRISTMAS PUDDING TRINKET POT,12,0.0,14110.0,United Kingdom
436961,574252,M,Manual,1,0.0,12437.0,France
439361,574469,22385,JUMBO BAG SPACEBOY DESIGN,12,0.0,12431.0,Australia

In [116]:
sem_cliente_preco_zero = vendas_preco_zero[
    vendas_preco_zero["CustomerID"].isnull()
]

sem_cliente_preco_zero[
    "Description"
].isnull().value_counts()

Description
True     592
False    542
Name: count, dtype: int64

In [117]:
sem_cliente_preco_zero[
    sem_cliente_preco_zero["Description"].notnull()
][
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "UnitPrice",
        "InvoiceDate",
        "Country"
    ]
].sample(30, random_state=42)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,InvoiceDate,Country
242420,558340,22676,FRENCH BLUE METAL DOOR SIGN 1,3,0.0,2011-06-28 14:01:00,United Kingdom
41445,539856,20682,RED RETROSPOT CHILDRENS UMBRELLA,2,0.0,2010-12-22 14:41:00,United Kingdom
242413,558340,22684,FRENCH BLUE METAL DOOR SIGN 9,1,0.0,2011-06-28 14:01:00,United Kingdom
41459,539856,22690,DOORMAT HOME SWEET HOME BLUE,2,0.0,2010-12-22 14:41:00,United Kingdom
160541,550460,47556B,did a credit and did not tick ret,1300,0.0,2011-04-18 13:18:00,United Kingdom
41450,539856,84968E,SET OF 16 VINTAGE BLACK CUTLERY,1,0.0,2010-12-22 14:41:00,United Kingdom
123995,546933,85099B,JUMBO BAG RED RETROSPOT,2,0.0,2011-03-18 11:02:00,United Kingdom
478930,577117,22149,check,34,0.0,2011-11-17 18:04:00,United Kingdom
524375,580549,84876B,found,66,0.0,2011-12-05 09:54:00,United Kingdom
497489,578374,21937,found,50,0.0,2011-11-24 11:21:00,United Kingdom
14339,537534,48111,DOORMAT 3 SMILEY CATS,1,0.0,2010-12-07 11:48:00,United Kingdom
124001,546933,22682,FRENCH BLUE METAL DOOR SIGN 7,3,0.0,2011-03-18 11:02:00,United Kingdom
313670,564530,22676,FRENCH BLUE METAL DOOR SIGN 1,3,0.0,2011-08-25 14:57:00,United Kingdom
41447,539856,18098C,PORCELAIN BUTTERFLY OIL BURNER,2,0.0,2010-12-22 14:41:00,United Kingdom
489195,577953,23348,check,5,0.0,2011-11-22 12:09:00,United Kingdom
170485,551304,48189,adjustment,2,0.0,2011-04-27 14:56:00,United Kingdom
433698,573989,23091,check,2,0.0,2011-11-02 11:14:00,United Kingdom
41474,539856,22650,CERAMIC PIRATE CHEST MONEY BANK,1,0.0,2010-12-22 14:41:00,United Kingdom
519355,580145,22925,AMAZON,1,0.0,2011-12-02 10:03:00,United Kingdom
14389,537534,20726,LUNCH BAG WOODLAND,1,0.0,2010-12-07 11:48:00,United Kingdom
104274,545160,22559,SEASIDE FLYING DISC,1,0.0,2011-02-28 13:31:00,United Kingdom
254132,559296,23298,SPOTTY BUNTING,170,0.0,2011-07-07 12:35:00,United Kingdom
41491,539856,22375,AIRLINE BAG VINTAGE JET SET BROWN,3,0.0,2010-12-22 14:41:00,United Kingdom
242408,558340,85099B,JUMBO BAG RED RETROSPOT,1,0.0,2011-06-28 14:01:00,United Kingdom
489150,577949,21804,check,44,0.0,2011-11-22 12:09:00,United Kingdom
14335,537534,85064,CREAM SWEETHEART LETTER RACK,1,0.0,2010-12-07 11:48:00,United Kingdom
41505,539856,21539,RED RETROSPOT BUTTER DISH,3,0.0,2010-12-22 14:41:00,United Kingdom
313657,564530,22427,ENAMEL FLOWER JUG CREAM,1,0.0,2011-08-25 14:57:00,United Kingdom
14343,537534,22681,FRENCH BLUE METAL DOOR SIGN 6,2,0.0,2010-12-07 11:48:00,United Kingdom
104405,545176,22363,GLASS JAR MARMALADE,1,0.0,2011-02-28 14:19:00,United Kingdom

In [118]:
sem_cliente_preco_zero["StockCode"].nunique()

654

In [119]:
sem_cliente_preco_zero["StockCode"].unique()

array([22139, 21134, 22145, 37509, '85226A', 85044, 20950, 37461, 84670,
       '84952C', 22734, 35951, 21421, 21651, 21777, 85215, 84270, 90167,
       22959, 37474, 85064, 84832, 84692, 48184, 48111, 22697, 22682,
       22680, 22681, 22679, 22686, 22683, 22676, 22625, 22624, 22619,
       22520, 22524, 22502, 22501, 22476, 22473, 22474, 22472, 22514,
       22516, 22432, 22428, 22427, 22376, 22375, 22372, 22371, 22620,
       22109, 22367, 22366, 22364, 22362, 22360, 22361, 22359, 22353,
       22350, 22327, 21116, 22202, 22550, 21912, 21891, 21559, 21531,
       20726, 20652, 20615, 21232, 21595, '85170A', 20849, 84977, 21661,
       '72803B', 35958, 22114, 21690, 21488, 84688, 22585, 21357, 84497,
       '90042C', '17091A', 84773, '85018C', 20878, 21186, '62095B', 72814,
       '84802A', '90002D', 22218, '84247C', '84534B', '90042B', 20956,
       85084, '35004P', 22444, 21479, 22112, 22356, 22591, 71477, 35400,
       21491, 21009, '85135B', 22652, 21080, 21481, 20682, 20724,
       '18098C', '85123A', '84968E', '84872A', 22518, 79321, 48194, 37333,
       22843, 22842, 22690, '85099B', 22685, 22684, 22678, 22677, 22666,
       22665, 22650, 22647, 22626, 22526, 22525, 22512, 22475, 22431,
       22426, 22374, 22357, 22072, 21791, 21888, 21539, 21258, 20719,
       84689, 84675, 90112, 35957, 21644, 22837, 20748, 21667, 82605,
       '84562A', 'POST', 21670, 21673, 22423, 22323, 21632, 21348, 84823,
       21324, '84279B', 84452, 37413, '79063D', 20798, 37467, '85049B',
       22830, '75013B', 22866, '35607A', '17165D', '84795C', 22242,
       '47591B', '79063C', '79062D', 22833, 35645, '84611B', 84306,
       '16207B', 21429, 85150, 22451, 21655, '85232B', 16033, 22865,
       '84029E', 22627, 22559, 22470, 22365, 22363, 22300, 22064, 20685,
       22383, '85099F', 21899, 22699, 22698, 22689, 22649, '15058A',
       '84459B', 21973, 37468, 21736, '90200C', '84535A', '84247K', 84988,
       '79302M', 85045, 21484, '84029G', 21555, '85185B', 85096, '46000S',
       '46000M', 22467, 23348, 22692, 22623, 22521, 22430, 22631, 21556,
       22272, '77101A', 22838, '85206A', '85028L', '85028S', 21717, 85197,
       21826, 84840, 21841, 22764, 84227, '84968B', 90084, '90005A',
       '85025C', 20973, '47593A', '35809B', 21621, 21898, '37444C',
       '37444B', 21393, 21445, 71038, 20713, 'DOT', 20734, 21614, 90104,
       10002, 21095, 20702, 84906, 15030, '90010A', '90082B', '84596E',
       '72800D', '72801G', 22720, '84507B', '84741C', 21278, 21279,
       '16248B', '82494L', 20760, 22988, '35819B', 21664, '84247L', 44265,
       20821, '84912A', 35914, '17014A', '84857C', '84858C', '62043B',
       85146, 22168, 21527, 22847, '47556B', '35915C', 84388, '85027L',
       22469, 84990, 22867, 21319, '17109D', '84531A', '84531B', 20941,
       84921, 85200, 85145, 21911, 22632, 85008, 22777, 82483, '51020A',
       48189, 22459, 21897, 22719, '85017C', 16015, 22173, 21269,
       '84873A', 84539, 21355, 84685, 47589, 20778, 20851, 23200, 23202,
       23203, 23209, '84596J', 20735, 22617, 37327, 84375, 84969, 20964,
       22726, 21143, 21181, 22646, 22644, 22645, 22637, 22519, 22515,
       22414, 22301, 22203, 21889, 22425, 22201, 21922, 20711, 22523,
       22522, 22078, '37444A', 22087, 82599, '84760S', 23444, 20886,
       20966, '85185D', '84313C', 79164, 20975, '47566B', 84746, 85214,
       35653, 20664, 85016, 16049, 20801, 21904, 84691, 84917, '84796B',
       20731, 21027, '47021G', 22968, '37479B', 22783, 84548, 21784,
       'gift_0001_20', 35965, 85141, 21937, 22084, 85213, '84387A', 22385,
       22380, '84709B', '47013C', 21082, 21145, 23574, 35966, 84944,
       '84857B', 84686, 20716, 82583, 23001, 22616, 23298, 21147, 23283,
       21763, 79337, 21067, 21578, 23343, '16162L', '16162M', 23196,
       35968, 21635, 21069, '84925F', 21272, 21472, 22080, 22088,
       '85086A', 22034, 21686, '35819P', 84789, '84402B', 23084, 10080,
       21868, '81952B', 21294, '84595E', '79161A', '40046A', 77079, 21275,
       79336, 21609, 72709, 84847, 22171, 23134, 22722, 79000, 21359,
       22194, 21658, 21033, '85049D', 85152, 20774, 85106, 85107, 20684,
       21172, 21900, 21901, 21561, 21452, 'gift_0001_30', 'gift_0001_10',
       22157, 16046, 23284, 48116, 21662, 23175, 37501, 21257, '85032D',
       23135, 37342, 21682, '84989A', '47570B', '85232D', 22355, '84660C',
       23306, 22035, 22823, 79163, 22050, 72127, 21830, 84929, '35815P',
       '35598C', '35592T', '35597D', '35598A', '84875D', '84877D',
       '90209C', '35911A', '84663A', 22740, 20984, 21349, 22829, '84660A',
       23268, 21586, 21587, 22062, 37370, '84849D', '90209B', 21394,
       22688, 22570, '47504K', 35933, 23412, 21244, '84247E', 21098,
       21918, '16168M', 21311, '84596G', '72802A', 21190, '46775D', 23702,
       22149, 23579, 21801, 22729, 85211, 21738, 20665, 20967, '79030D',
       23595, '35810B', '82613A', 72818, 21829, '84507C', 20754, 22687,
       '72803A', 21794, '35600A', 21174, '85135A', 23400, 22117, 21192,
       '46000U', 22812, 23131, 22121, 84050, '47503A', 21700, 82600,
       '16207A', 22848, '84659A', 22925, 23091, 22606, 21804, 22180,
       21071, 85054, '85017B', '84279P', 'C2', 35954, 22827, 21809,
       '17012F', 21051, 21054, 21823, 85127, 22548, '85019B', 72817,
       21915, 22759, 20832, '72802C', '47503H', 85125, '15060B', 23118,
       '85231G', 21811, 21992, '17136A', '37489A', 22125, 22568, '84971L',
       22579, 23541, 22943, '85034A', 23157, '72807A', 22176, 22810,
       '85135C', 22533, 21927, 22947, 22696, 22923, 23169, '84876B',
       21808, 22927, 21803, 23404, 23406, 21620, 22142, 85175],
      dtype=object)

In [120]:
sem_cliente_preco_zero["StockCode"].value_counts()

StockCode
23084    13
35965    11
22676     9
22683     8
20713     8
         ..
23404     1
23406     1
21620     1
22142     1
85175     1
Name: count, Length: 654, dtype: int64

In [121]:
df_transformado[
    [
        "InvoiceNo",
        "Quantity",
        "UnitPrice",
        "tipo_transacao",
        "valor_total"
    ]
].head(20)

   InvoiceNo  Quantity  UnitPrice tipo_transacao  valor_total
0     536365         6       2.55          VENDA        15.30
1     536365         6       3.39          VENDA        20.34
2     536365         8       2.75          VENDA        22.00
3     536365         6       3.39          VENDA        20.34
4     536365         6       3.39          VENDA        20.34
5     536365         2       7.65          VENDA        15.30
6     536365         6       4.25          VENDA        25.50
7     536366         6       1.85          VENDA        11.10
8     536366         6       1.85          VENDA        11.10
9     536367        32       1.69          VENDA        54.08
10    536367         6       2.10          VENDA        12.60
11    536367         6       2.10          VENDA        12.60
12    536367         8       3.75          VENDA        30.00
13    536367         6       1.65          VENDA         9.90
14    536367         6       4.25          VENDA        25.50
15    536367         3       4.95          VENDA        14.85
16    536367         2       9.95          VENDA        19.90
17    536367         3       5.95          VENDA        17.85
18    536367         3       5.95          VENDA        17.85
19    536367         4       7.95          VENDA        31.80

In [122]:
df_transformado["valor_total"].describe()

count    536641.000000
mean         18.123861
std         380.656263
min     -168469.600000
25%           3.750000
50%           9.870000
75%          17.400000
max      168469.600000
Name: valor_total, dtype: float64

In [123]:
maiores_valores = df_transformado.nlargest(10, "valor_total")

menores_valores = df_transformado.nsmallest(10, "valor_total")

In [124]:
colunas_analise = [
    "InvoiceNo",
    "StockCode",
    "Description",
    "Quantity",
    "UnitPrice",
    "tipo_transacao",
    "valor_total"
]

In [125]:
maiores_valores[colunas_analise]

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,tipo_transacao,valor_total
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2.08,VENDA,168469.60
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1.04,VENDA,77183.60
222680,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,649.50,VENDA,38970.00
15017,537632,AMAZONFEE,AMAZON FEE,1,13541.33,VENDA,13541.33
299982,A563185,B,Adjust bad debt,1,11062.06,VENDA,11062.06
173382,551697,POST,POSTAGE,1,8142.75,VENDA,8142.75
348325,567423,23243,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,5.06,VENDA,7144.72
52711,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,VENDA,6539.40
160546,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,VENDA,6539.40
421601,573003,23084,RABBIT NIGHT LIGHT,2400,2.08,VENDA,4992.00

In [126]:
menores_valores[colunas_analise]

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,tipo_transacao,valor_total
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2.08,CANCELAMENTO,-168469.60
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,1.04,CANCELAMENTO,-77183.60
222681,C556445,M,Manual,-1,38970.00,CANCELAMENTO,-38970.00
524602,C580605,AMAZONFEE,AMAZON FEE,-1,17836.46,CANCELAMENTO,-17836.46
43702,C540117,AMAZONFEE,AMAZON FEE,-1,16888.02,CANCELAMENTO,-16888.02
43703,C540118,AMAZONFEE,AMAZON FEE,-1,16453.71,CANCELAMENTO,-16453.71
15016,C537630,AMAZONFEE,AMAZON FEE,-1,13541.33,CANCELAMENTO,-13541.33
16356,C537651,AMAZONFEE,AMAZON FEE,-1,13541.33,CANCELAMENTO,-13541.33
16232,C537644,AMAZONFEE,AMAZON FEE,-1,13474.79,CANCELAMENTO,-13474.79
524601,C580604,AMAZONFEE,AMAZON FEE,-1,11586.50,CANCELAMENTO,-11586.50

## Implementação e testes das regras de transformação

Após a etapa de exploração e definição das regras de negócio, as transformações identificadas foram implementadas individualmente no módulo `src/transform.py`.

Cada função foi criada e testada separadamente no notebook antes de ser incorporada ao fluxo completo de transformação.

### Funções implementadas

- `remove_duplicates(df)`  
  Remove registros completamente duplicados do dataset.

- `define_cancelamento(df)`  
  Identifica os registros de cancelamento e cria a coluna booleana `cancelado`.

- `define_ajuste_estoque(df)`  
  Identifica movimentações relacionadas a ajustes de estoque e cria a coluna booleana `ajuste_estoque`.

- `define_tipo_transacao(df)`  
  Utiliza as regras anteriores para classificar os registros em:
  - `VENDA`
  - `CANCELAMENTO`
  - `AJUSTE_DE_ESTOQUE`

- `calcula_valor_total(df)`  
  Cria a coluna `valor_total` através do cálculo:

  `Quantity × UnitPrice`

### Estratégia de desenvolvimento

As funções foram implementadas de forma incremental.

Após a criação de cada função, seu resultado foi testado no notebook antes de prosseguir para a próxima transformação.

Esse processo permitiu validar separadamente cada regra e verificar se os resultados obtidos estavam de acordo com o comportamento identificado durante a exploração dos dados.

Após os testes individuais, as funções foram reunidas em uma única função responsável por coordenar toda a etapa de transformação:

`transform_data(df)`

A função executa as transformações na sequência definida:

`remove_duplicates()`

↓  

`define_cancelamento()`

↓  

`define_ajuste_estoque()`

↓  

`define_tipo_transacao()`

↓  

`calcula_valor_total()`

↓  

**DataFrame transformado**

Com isso, as regras que inicialmente foram descobertas e testadas individualmente no notebook passaram a fazer parte de um processo de transformação reutilizável.

### Resultado

O notebook foi utilizado como ambiente de experimentação para:

**investigar → definir regras → implementar → testar**

Enquanto o módulo `src/transform.py` passou a concentrar as regras de transformação que poderão ser reutilizadas pela pipeline.

A validação da função completa `transform_data()` será realizada separadamente no notebook `02-validacao-transformacoes.ipynb`.